//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoukashRevamp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int users_id { get; set; }
        public int companies_id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
