//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoukashRevamp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.Role_Permission = new HashSet<Role_Permission>();
        }
    
        public int id { get; set; }
        public string menu { get; set; }
    
        public virtual ICollection<Role_Permission> Role_Permission { get; set; }
    }
}
