//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoukashRevamp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Role_Permission = new HashSet<Role_Permission>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int companies_id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Role_Permission> Role_Permission { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
